{% set name = "TracyWidom" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: b972a296393eb4e101e418db64b36200e0315ece717b6955966f33692c46762f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.7.0
    - scipy >=0.13.0

test:
  imports:
    - TracyWidom
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yymao/TracyWidom
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate Tracy-Widom distribution functions (beta=1,2,4) in Python
  doc_url: https://github.com/yymao/TracyWidom/blob/main/README.md
  dev_url: https://github.com/yymao/TracyWidom

extra:
  recipe-maintainers:
    - yymao
